### ISSUE TITLE
Cannot find module 'playwright'

### ISSUE THREAD

**Issue by ghost** [Commandtechno/Scarbon#1]
```js
(node:762) UnhandledPromiseRejectionWarning: Error: Cannot find module 'playwright'
Require stack:
- /home/runner/miwa-main-api/node_modules/shiki-renderer-svg/dist/index.js
- /home/runner/miwa-main-api/node_modules/scarbon/index.js
- /home/runner/miwa-main-api/src/routes/canvas/code.js
- /home/runner/miwa-main-api/src/routes/canvas/index.js
- /home/runner/miwa-main-api/src/routes/index.js
- /home/runner/miwa-main-api/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at measureMonospaceTypeface (/home/runner/miwa-main-api/node_modules/shiki-renderer-svg/dist/index.js:61:28)
    at getSVGRenderer (/home/runner/miwa-main-api/node_modules/shiki-renderer-svg/dist/index.js:89:31)
    at /home/runner/miwa-main-api/node_modules/scarbon/index.js:88:9
    at Object.theme.then (/home/runner/miwa-main-api/node_modules/scarbon/index.js:335:32)
    at new module.exports (/home/runner/miwa-main-api/node_modules/scarbon/index.js:80:24)
    at /home/runner/miwa-main-api/src/routes/canvas/code.js:31:24
```

**Comment by ni3mumbaikar** [comment]
tried `yarn add playwright` but then it gives the following error when I am reading a .java file.

![image](https://user-images.githubusercontent.com/24763651/194748322-a0d41f3d-f6b1-4d0d-9ac8-f160966da97d.png)

is there any issue with prettier ?

**Comment by Commandtechno** [comment]
hi, i have not been able to work on this project recently, so sorry for the issues

this error does look like its from prettier, as far as i know prettier does not support formatting java files, does disabling prettier with {formatter: {disabled: true}} help with this

i'm not exactly sure why i added prettier to this so i may try and rewrite this and remove prettier all together

**Comment by ni3mumbaikar** [comment]
np @Commandtechno 👍  ,
I also tried disabling prettier but then the formatting got disturbed even with the formatted string.

available alternative : [unofficial-carbon-now-sh](https://www.npmjs.com/package/unofficial-carbon-now-sh)
